# Exported from Render on 2024-07-27T02:54:23Z
services:
  - type: web
    name: api-avengers
    runtime: docker
    repo: https://github.com/LeonardoJaques/api-avengers
    plan: free
    envVars:
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_USER
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
